_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/private/few-shot-object-detection-master/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2012_trainval_base1',)
  TEST: ('voc_2012_test_base1',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
OUTPUT_DIR: "/private/FSCE-main/checkpoints/faster_rcnn_R_101_FPN_base1_test_NWPU"
